spring.application.name=CooperativeDevelopment
server.port=8080

# PRIMARY DATABASE (Government)
mongodb.primary.uri=${MONGODB_PRIMARY_URI}

# SECONDARY DATABASE (Coop_Leave)
mongodb.secondary.uri=${MONGODB_SECONDARY_URI}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=centeral.gov.coop@gmail.com
spring.mail.password=dvcj bwsm rpxm ueep
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true